services:
  - type: web
    name: crypto-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PORT
        value: 10000