services:
  - type: web
    name: crypto-prediction-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn wsgi:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://crypto-prediction-frontend.vercel.app
      - key: CORS_HEADERS
        value: Content-Type,Authorization