services:
  - type: web
    name: crypto-prediction-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: CORS_ALLOWED_ORIGINS 
        value: "https://crypto-prediction-frontend-e0brht1kb-abhiram-aroops-projects.vercel.app,https://crypto-prediction-frontend.vercel.app,http://localhost:3000"