services:
  - type: web
    name: crypto-prediction-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production