services:
  - type: web
    name: crypto-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11