services:
  - type: web
    name: crypto-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PYTHONPATH
        value: /opt/render/project/src