services:
  - type: web
    name: crypto-prediction-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn wsgi:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 4
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80